project:
  type: website

website:
  title: "Occupancy Modelling"
  site-url: https://deonroos.github.io/Occupancy_Modelling/
  navbar:
    left:
      - text: "Occupancy Models: The basics"
        href: Occupancy_Models.qmd
      - text: "Occupancy Models: Covariates"
        href: OccMods_WithCovariates.qmd
      - text: "Bayesian models: The concept"
        href: Bayesian_Statistics.qmd
      - text: "Fitting Bayesian models"
        href: Bayesian_Occupancy_Models.qmd

format:
  html:
    theme: cosmo
    toc: true
