<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Deon Roos">
<meta name="dcterms.date" content="2025-05-03">

<title>Occupancy Modelling - Introduction to Occupancy Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Occupancy Modelling</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./Occupancy_Models.html" rel="" target="" aria-current="page">
 <span class="menu-text">Occupancy Models: The basics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./OccMods_WithCovariates.html" rel="" target="">
 <span class="menu-text">Occupancy Models: Covariates</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Bayesian_Statistics.html" rel="" target="">
 <span class="menu-text">Bayesian models: The concept</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Bayesian_Occupancy_Models.html" rel="" target="">
 <span class="menu-text">Fitting Bayesian Models</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#where-are-species-present-and-why-are-they-present" id="toc-where-are-species-present-and-why-are-they-present" class="nav-link active" data-scroll-target="#where-are-species-present-and-why-are-they-present">Where are species present and why are they present?</a></li>
  <li><a href="#imperfect-detection" id="toc-imperfect-detection" class="nav-link" data-scroll-target="#imperfect-detection">Imperfect detection</a></li>
  <li><a href="#occupancy-models" id="toc-occupancy-models" class="nav-link" data-scroll-target="#occupancy-models">Occupancy models</a>
  <ul class="collapse">
  <li><a href="#state-model" id="toc-state-model" class="nav-link" data-scroll-target="#state-model">State model</a></li>
  <li><a href="#observation-model" id="toc-observation-model" class="nav-link" data-scroll-target="#observation-model">Observation model</a></li>
  </ul></li>
  <li><a href="#the-robust-design-and-closure" id="toc-the-robust-design-and-closure" class="nav-link" data-scroll-target="#the-robust-design-and-closure">The robust design and closure</a></li>
  <li><a href="#the-assumption-of-closure" id="toc-the-assumption-of-closure" class="nav-link" data-scroll-target="#the-assumption-of-closure">The assumption of closure</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The data</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data preparation</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">Fitting the model</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results">Interpreting the results</a></li>
  <li><a href="#what-next" id="toc-what-next" class="nav-link" data-scroll-target="#what-next">What next?</a></li>
  <li><a href="#lecture-recording" id="toc-lecture-recording" class="nav-link" data-scroll-target="#lecture-recording">Lecture recording</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to Occupancy Models</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Deon Roos </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="where-are-species-present-and-why-are-they-present" class="level1">
<h1>Where are species present and why are they present?</h1>
<p>A fundamental question in ecology is; Where are species present, and why are they present <em>there</em>?</p>
<blockquote class="blockquote">
<p><strong>Zitong</strong>, in your case this may be; Why are roe deer present at site A but not site B? Is it because site A is closer to roads? If a site is close to a road what’s the probability roe deer are present? Is that very different to sites that are far away from a road?</p>
<p>What about features of the habitat? Are roe deer more likely if a site is forested versus agricultural?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Joe</strong>, in your case this may be; Why are pheasants present at site A but not site B? Is it related to how far away the nearest <em>known</em> release pen is? What does the relationship look like? If there is no relationship, what would that mean for policy?</p>
<p>What about the habitat makes pheasants more likely to occupy that site?</p>
</blockquote>
<p>To act as motivation for this intro to occupancy models, let’s say we’re interested in understanding why are elephants present in the north of <a href="https://www.etoshanationalpark.org/">Etosha</a> nature reserve in Namibia, but not in the south of the reserve? (As a side note, I’d recommend going there on holiday if you ever get the chance). Are elephants present in some parts of Etosha due to water availability? Is it related to food? Could predators play a role?</p>
<p>To find out, we need stats. As useful as gut feelings and intuition are, it’s not enough. Remember, <em>statistics is how we get the <strong>evidence</strong></em> <em>to answer our research question using data</em>.</p>
<p>The best statistical tool available for answering these types of questions are “occupancy modeling”. These were originally developed by Daryl MacKenzie et al in <a href="https://doi.org/10.1890/0012-9658(2002)083%5B2248:ESORWD%5D2.0.CO;2">2002</a> who wanted to deal with a subtle issue when trying to find animals (more on this in a second). The broad concept underlying MacKenzie’s occupancy modelling framework built on ideas that had already been developed for estimating <em>survival</em> <em>of</em> <em>individual</em> animals, called the Cormack-Jolly-Seber, or CJS, model. As a cool note; Cormack and Jolly independently developed this model <em>while they worked in Aberdeen University</em> - a vital and internationally renowned model was developed right here in bloody Aberdeen! In my entire time as an undergraduate student, then as a PhD <em>in Aberdeen</em> no one ever told me this (even though I was taught these methods in Aberdeen)! I only found out at a conference in France years after leaving Aberdeen. As a school, we should be far more proud of this than we are.</p>
<p>The problem that occupancy models solve is subtle, yet absolutely crucial. Occupancy models estimate the probability a species occupies a site, <strong>and also</strong> the probability that you see them.</p>
<p>Assume I want to determine where elephants are present in Etosha nature reserve in Namibia. I need data to answer this, so I decide to do ten elephant surveys in Etosha. Specifically, I go to visit these ten sites that are nicely spread throughout the park. At each site, whenever I spot an elephant I note down that elephants are present at that location. When I don’t see any elephants I record that elephants are absent at that location. Simple, right?</p>
<p>Let’s imagine we collect data across ten sites. Here’s what our dataset might look like:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1988</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>etosha <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">site =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">elephants =</span> <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.4</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>etosha</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   site elephants
1     1         0
2     2         0
3     3         0
4     4         0
5     5         0
6     6         0
7     7         0
8     8         1
9     9         1
10   10         0</code></pre>
</div>
</div>
<p>When <code>elephants</code> is <code>1</code>, it means elephants were seen at that site; when it’s <code>0</code>, they were not. So, <code>1</code> indicates presence, and <code>0</code> indicates absence; at least for now.</p>
<p>To figure out the average probability that any one of my ten sites are occupied, I can run a Bernoulli Generalised Linear Model. The Bernoulli distribution (named after <a href="https://en.wikipedia.org/wiki/Jacob_Bernoulli">Jacob Bernoulli</a>) generates values of <code>1</code> or <code>0</code>, which is perfect for our binary presence–absence data.</p>
<p>The model would be:</p>
<p><span class="math display">\[
y_i \sim Bernoulli(p_i) \\
\]</span></p>
<p><span class="math display">\[
logit(p_i) = \beta_0
\]</span></p>
<p>Let’s go through these equations slowly:</p>
<ul>
<li><p><span class="math inline">\(y\)</span> is our observation (<code>elephants</code> in the <code>etosha</code> dataset)</p></li>
<li><p><span class="math inline">\(i\)</span> is the index, here being which <code>site</code> the data was collected from</p></li>
<li><p><span class="math inline">\(\sim\)</span> means “generated according to” (or “our data is the same as would be generated by the following distribution”)</p></li>
<li><p><span class="math inline">\(Bernoulli\)</span> is a type of distribution that will generate either 0 or 1</p></li>
<li><p><span class="math inline">\(p\)</span> is the probability of success (i.e.&nbsp;there is <span class="math inline">\(p\)</span> probability that we see an elephant). We can’t possibly know what <span class="math inline">\(p\)</span> is when we collect the data, so we need to figure it out with statistics. (The <span class="math inline">\(i\)</span> means each site <em>could</em> have a different probability - but we’re not doing that yet)</p></li>
<li><p><span class="math inline">\(logit\)</span> is the link function to ensure that <span class="math inline">\(p\)</span> remains between 0% and 100%. Specifically, it’s a little bit of maths: <span class="math inline">\(log(\frac{p}{1-p})\)</span>, which is the natural log of the probability to succeed (<span class="math inline">\(p\)</span>) divided by the probability to fail (<span class="math inline">\(1-p\)</span>). More on this in a second.</p></li>
<li><p><span class="math inline">\(\beta_0\)</span> is the intercept. Since we haven’t included any covariates (yet), it captures the average logit value of elephant presence across all sites. When converted back from the logit scale, this will give us the average probability of elephant presence.</p></li>
</ul>
<p>To understand how the logit link transforms probabilities, have a look at this figure. It maps the full range of probabilities (0% to 100%) to the logit scale.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>logit <span class="ot">&lt;-</span> <span class="fu">log</span>(p<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(p, logit)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> logit, <span class="at">y =</span> p)) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Logit value that</span><span class="sc">\n</span><span class="st">elephants are present"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability that</span><span class="sc">\n</span><span class="st">elephants are present"</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Occupancy_Models_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Notice how as the probability approaches 0%, it never actually drops below it, even as the logit value keeps decreasing? And the same happens when it gets close to 100%. And that’s exactly what we want. The fact that logit values can range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span> makes model fitting much easier: it turns a bounded probability into an unbounded scale, allows linear relationships with predictors, and ensures valid probabilities when converting predictions back. So even if our model estimates a logit value of 999 billion, it still maps to a probability of 100%. This ensures the natural bounds of probability, which is between 0% and 100%, are always respected.</p>
<p>If you want a bit more detail and intuition, here is an old lecture recording that covers the logit link function:</p>
<iframe src="https://abdn.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=dea0921b-d1ce-49f4-84b9-acb700ef650f" width="720" height="405" allowfullscreen="">
</iframe>
<p>With that in mind, here’s how we’d fit our model in <code>R</code>. (Click <code>Code</code> to reveal the code.)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(elephants <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> etosha,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>This estimates <span class="math inline">\(\beta_0\)</span>, the average probability of elephant presence, but on the logit scale. We can see what it has been estimated as by looking at the summary of the model:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = elephants ~ 1, family = binomial(link = "logit"), 
    data = etosha)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -1.3863     0.7906  -1.754   0.0795 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 10.008  on 9  degrees of freedom
Residual deviance: 10.008  on 9  degrees of freedom
AIC: 12.008

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The estimate for <code>(Intercept)</code> (or <span class="math inline">\(\beta_0\)</span>) is <code>-1.3863</code>. Now that we have an estimate for <span class="math inline">\(\beta_0\)</span>, we can plug it into our model:</p>
<p><span class="math display">\[
y_i \sim Bernoulli(p_i) \\
\]</span></p>
<p><span class="math display">\[
logit(p_i) = -1.3863
\]</span></p>
<p>To interpret this on the probability scale, we apply the inverse logit transformation using <code>plogis()</code> in <code>R</code>:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">1.3863</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1999991</code></pre>
</div>
</div>
<p>This gives us a probability of approximately 0.2, or 20%, meaning there’s a 20% chance a site is occupied by elephants.</p>
<p>Or does it?</p>
</section>
<section id="imperfect-detection" class="level1">
<h1>Imperfect detection</h1>
<p>That 20% estimate isn’t as straightforward as “there’s a 20% chance a site has elephants.” It’s actually the result of two probabilities being multiplied together. For us to detect an elephant and get a <code>1</code> in the <code>etosha</code> dataset, two things need to happen.</p>
<ol type="1">
<li><p>The elephant must obviously be there, with some probability. We can call this probability <span class="math inline">\(\psi\)</span> (called “psi”, pronounced like “sigh”).</p></li>
<li><p>I also have to <em>see</em> the elephant, and no matter how good I am, that probability is almost certainly never going to be 100%. We normally call this probability <span class="math inline">\(p\)</span>.</p></li>
</ol>
<p>So all of the <code>1</code>’s in our <code>etosha</code> dataset are the result of succeeding in both of these probabilities. But a <code>0</code> could be the result from <strong>either</strong> of two failures:</p>
<ol type="1">
<li><p>either there truly were no elephants (<span class="math inline">\(1 - \psi\)</span> - remember <span class="math inline">\(\psi\)</span> is the probability there are elephants, e.g.&nbsp;20% or 0.2, in which case <span class="math inline">\(1-0.2 = 0.8\)</span> or 80% chance there are no elephants),</p></li>
<li><p>or elephants were present but we didn’t detect them (<span class="math inline">\(\psi \times (1 - p)\)</span> - remember that <span class="math inline">\(p\)</span> is the probability to detect a species, so if <span class="math inline">\(\psi = 0.2\)</span> and <span class="math inline">\(p = 0.6\)</span>, then the probability to <strong>not</strong> see them is <span class="math inline">\(0.2 * (1 - 0.6) = 0.08\)</span>, or “there is an 8% chance elephants are present but not detected).</p></li>
</ol>
<p>Fundamentally, the problem is that the data in the <code>elephants</code> column of our <code>etosha</code> dataset represents <span class="math inline">\(\psi \times p\)</span>, and not just <span class="math inline">\(\psi\)</span> like we want.</p>
<p>For example, here’s a picture from BI3010 that you might remember. I’ve added a white line to show where the elephant is almost perfectly obscured by an acacia tree. If this was at one of our sites in <code>etosha</code>, then we’d have recorded <code>0</code> (or said <code>Absent</code>) despite it being there.</p>
<p><img src="images/occupancy.PNG" class="img-fluid"></p>
<p>There’s no shortage of reasons why you might not see an elephant despite it being there. It can be as simple as the elephant was behind a bush when I checked that site. Or, if we were using cameras, it might be that the motion sensor didn’t trigger. Or it might be that the elephant was behind the camera. This process of an animal being present but us not seeing it reflects something called <em>imperfect detection</em>, i.e.&nbsp;just cause it’s there doesn’t mean we’re guaranteed to see it.</p>
<p><em>Imperfect detection</em> is not an issue for the <code>1</code>’s in our <code>etosha</code> data.</p>
<ul>
<li><p>If you see an elephant, you know there was an elephant present. That’s easy and obvious.</p></li>
<li><p>The complication happens when we <strong><em>don’t</em></strong> detect an elephant; when <code>elephants</code> is <code>0</code>.</p></li>
</ul>
<p>That’s the key problem: a <code>0</code> in the data doesn’t always mean “no elephants”, it could just mean we missed them.</p>
<p>Occupancy models don’t ignore this, they’re built to handle it. They allow us to estimate two things separately: the probability that a site is occupied (<span class="math inline">\(\psi\)</span>), and, if it is, the probability of detecting the species (<span class="math inline">\(p\)</span>).</p>
<p>That’s why they’re such a powerful tool. Here’s how they do it.</p>
</section>
<section id="occupancy-models" class="level1">
<h1>Occupancy models</h1>
<section id="state-model" class="level2">
<h2 class="anchored" data-anchor-id="state-model">State model</h2>
<p>The first part of an occupancy model is the <em>state model</em>, so called because it estimates the true state of each site: is the species present or absent?</p>
<p><span class="math display">\[
z_i \sim Bernoulli(\psi_i)\\
\]</span></p>
<p><span class="math display">\[
logit(\psi_i) = \beta_0
\]</span></p>
<p>This model probably looks similar. That’s because like the first model we spoke about further above, it’s also a <span class="math inline">\(Bernoulli\)</span> GLM. But they differ in two important ways:</p>
<ul>
<li><p><span class="math inline">\(z\)</span> is the <strong>true</strong> presence or absence of elephants in site <span class="math inline">\(i\)</span> (this isn’t <span class="math inline">\(y\)</span>)</p></li>
<li><p><span class="math inline">\(\psi\)</span> is the probability to be present</p></li>
</ul>
<p>That’s nice and all but just changing the labels doesn’t fix imperfect detection. To solve that, we need a second model: the <em>observation model</em>.</p>
</section>
<section id="observation-model" class="level2">
<h2 class="anchored" data-anchor-id="observation-model">Observation model</h2>
<p>The second GLM (which I’ll call the <em>observation model</em>) also looks remarkably similar:</p>
<p><span class="math display">\[
y_{i,j} \sim Bernoulli(p_{i,j} \times z_i)\\
\]</span></p>
<p><span class="math display">\[
logit(p_{i,j}) = \alpha_0
\]</span></p>
<p>It’s another <span class="math inline">\(Bernoulli\)</span> GLM but with some crucial differences.</p>
<ul>
<li><p><span class="math inline">\(y\)</span> is now the <strong>detection</strong> or not of an elephant. This is worth highlighting - <span class="math inline">\(y\)</span> is <strong>not</strong> the presence or absence of elephants, it’s the detection of elephants <strong>if</strong> they’re present!</p></li>
<li><p><span class="math inline">\(j\)</span> represents which <em>survey</em> <span class="math inline">\(y\)</span> was collected in, which inherently means we have <em>multiple surveys</em>, not just one like in our first GLM example above where <span class="math inline">\(i\)</span> was a single (of ten) sites. This has implications for how we collect data, which we’ll come back to.</p></li>
<li><p><span class="math inline">\(p\)</span> is the probability to detect an elephant at site <span class="math inline">\(i\)</span> in survey <span class="math inline">\(j\)</span> (e.g.&nbsp;what is the probability to detect an elephant in site 1 in the third survey?)</p></li>
</ul>
<p>Importantly, the probability to detect elephants (<span class="math inline">\(p\)</span>) is <em>multiplied</em> by <span class="math inline">\(z\)</span>. What’s <span class="math inline">\(z\)</span>? Well that’s the true occupancy state of that site from the <em>state model</em>. It’s this multiplication that allows the two models to “speak” to each other, and how we deal with imperfect detection; it ensures the <em>observation process</em> depends on whether the species is actually present.</p>
<p>If there are elephants in a site (<span class="math inline">\(z = 1\)</span>), then <span class="math inline">\(p \times z = p \times 1 = p\)</span>. If elephants are absent from a site (<span class="math inline">\(z = 0\)</span>), then <span class="math inline">\(p \times z = p \times 0 = 0\)</span>. This means <em>you cannot detect elephants if they aren’t there</em>. That’s blindingly obvious… It’s so dumb that most people don’t realise you need to specify it (I’ve heard people say: “surely any model can figure this out?”). But this stupidly simple logic is missing from our starting GLM! And a lot of research asking about where species are use a model equivalent to the very first GLM on this page.</p>
<blockquote class="blockquote">
<p>Keep in mind that we don’t know <span class="math inline">\(z\)</span>. That’s the true occupancy state, a <em>latent variable</em>. Latent just means it’s unobserved: we can’t measure <span class="math inline">\(z\)</span> directly in the field, but we can estimate it using the data we collect, much like we do with parameters.</p>
</blockquote>
<p>That’s how occupancy models “know” that you can only detect elephants if they’re present, and that if they’re absent, you won’t detect them. It seems so obvious, yet this logic is missing from many models that treat non-detections as true absences.</p>
<p>And that’s the beauty of occupancy models. They handle the messy reality of ecological data (but can also be used in e.g.&nbsp;medicine), and that’s why they’re one of my favorite types of analysis.</p>
</section>
</section>
<section id="the-robust-design-and-closure" class="level1">
<h1>The robust design and closure</h1>
<p>So, we have a clever modeling framework, but how does it help when we go to a site and don’t see any elephants? How can we tell the difference between a true negative (the site was genuinely unoccupied) and a false negative (elephants were present, but we missed them)?</p>
<p>This is where the subscript <span class="math inline">\(j\)</span> in the observation model becomes important. If you only visit a site once and don’t see any elephants, you’re left guessing. With no extra information, you can’t know whether the site was unoccupied or whether you simply failed to detect them.</p>
<p>But imagine I went back to that same site the next day. This time I do see elephants. We learn a few things from this. First, we know elephants are present at the site. Secondly, we learn that the first survey must have been a false negative - we just didn’t see elephants despite them being there.</p>
<p>Now imagine we scale this up by repeating this process where we now survey each of the ten sites three times. What might that data look like?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1988</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>psi <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.8</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(N, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">p =</span> psi)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">nrow =</span> N, <span class="at">data =</span> <span class="dv">0</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Specifying y manually so it's easier to use in text</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># for (i in 1:N){ # For each site</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   for (j in 1:3) { # For each survey</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co">#     y[i, j] &lt;- rbinom(1, 1, prob = z[i] * p)</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co">#   } # survey j</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># } # site i</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>y[<span class="dv">1</span>,<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>y[<span class="dv">8</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>y[<span class="dv">9</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>etosha <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(y)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>etosha<span class="sc">$</span>site <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(etosha) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Survey 1"</span>, <span class="st">"Survey 2"</span>, <span class="st">"Survey 3"</span>, <span class="st">"Site"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>etosha <span class="ot">&lt;-</span> etosha[, <span class="fu">c</span>(<span class="st">"Site"</span>, <span class="st">"Survey 1"</span>, <span class="st">"Survey 2"</span>, <span class="st">"Survey 3"</span>)]</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>highlight_ones <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>         <span class="fu">cell_spec</span>(x,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>                   <span class="at">background =</span> <span class="st">"darkred"</span>,</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bold =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>         x)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>etosha_kbl <span class="ot">&lt;-</span> etosha</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>etosha_kbl[, <span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(etosha_kbl[, <span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], highlight_ones)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(etosha_kbl, <span class="st">"html"</span>, <span class="at">escape =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Site</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Survey 1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Survey 2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Survey 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;"><span style=" font-weight: bold;    color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: darkred !important;">1</span></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;"><span style=" font-weight: bold;    color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: darkred !important;">1</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;"><span style=" font-weight: bold;    color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: darkred !important;">1</span></td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>By surveying each site three times, we gain crucial extra information to help account for imperfect detection.</p>
<p>We detect elephants in three sites:</p>
<ul>
<li><p>Site 1 in survey 1</p></li>
<li><p>Site 8 in survey 3</p></li>
<li><p>Site 9 in survey 2</p></li>
</ul>
<p>From this, we know there are definitely elephants in sites 1, 8 and 9. But we also learn some additional information that’s going to be very useful. In sites 1, 8 and 9, we see elephants only once out of three attempts in each site. Since we <em>know</em> elephants are present at those sites (we saw them at least once), and yet we only detected them in 1 out of 3 visits, we can estimate detection probability as roughly 30%.</p>
<p>Now let’s consider a site where we never detected elephants, say, site 2. What’s the chance that elephants were actually there, but we just missed them every time? Well, we’ve manually estimated our detection probability at 30% meaning the probability not to detect them is 100% - 30%, or 1-0.3, so the probability <strong>not to detect</strong> them on every single one of the three surveys is:</p>
<p><span class="math display">\[(1-0.3) \times (1-0.3) \times (1-0.3) = (1-0.3)^3=0.343=34\%\]</span></p>
<p>So even if elephants are present, there’s a 34% chance we’d miss them on all three surveys. That’s not trivial and it shows how easily a site could look empty even when it’s not.</p>
<p>This introduces a key assumption in occupancy models. But for that 30% detection probability to be meaningful, we must make an important assumption, called the <em>closure assumption</em>. This means we assume that if a site is occupied, it was occupied for all three surveys. In other words, the <code>0</code>s in sites 1, 8, and 9 were false negatives and not times when the elephants just happened to leave that site for a day. For example, we assume the elephants in site 8 didn’t just wander in before the third survey; they <em>were</em> there during the first and second surveys too.</p>
</section>
<section id="the-assumption-of-closure" class="level1">
<h1>The assumption of closure</h1>
<p>This is known as the <em>assumption of closure</em> (or <em>closure assumption</em>). It’s often misunderstood as meaning the site is physically “closed” off by something like a fence to prevent animals from entering and leaving. That’s not what it means. In occupancy models, closure means the population is demographically closed during the survey period. If a species is present at the first survey, it remains present for all subsequent surveys.</p>
<blockquote class="blockquote">
<p><strong>Zitong</strong> and <strong>Joe</strong>, this has two important implications for your fieldwork:</p>
<p>You need to survey each site on multiple occasions, i.e.&nbsp;you need <span class="math inline">\(J\)</span> surveys. If you’re using camera traps, this means leaving the camera in situ for more than one sampling period.</p>
<p>You’re completely free to define the sampling period (hour/day/week), but it must be short enough that if your species is present at the first survey, it’s still present at the last.</p>
</blockquote>
<p>And, critically, the full survey period should not be so long that the species could realistically disappear from the site (e.g.&nbsp;due to death, migration, or disturbance) or recolonise it.</p>
<p>In practice, you need at least three survey occasions to estimate detection probability reliably. These could be three days, three 12-hour periods—whatever matches your chosen sampling unit. More surveys are great (e.g.&nbsp;two weeks of camera trapping), but be cautious: surveying over too long a period risks violating closure if the species could move in or out of the site (or go locally extinct or recolonise a vacant site).</p>
<p>This approach, repeatedly surveying the same site at least three times within a “closed” window, is called the robust design. It’s the backbone of reliable single-season occupancy modeling, and something you should aim to implement whenever possible.</p>
</section>
<section id="the-data" class="level1">
<h1>The data</h1>
<p>I’m going to simulate data for an occupancy model to show you how your data should be structured, and to give you something to practise with. We’ll use the <code>spOccupancy</code> package in <code>R</code> which you’ll also use in your own analysis. It stands for <em>spatial occupancy</em>, but we’ll focus on the <em>occupancy</em> part for now and save the <em>spatial</em> component for later.</p>
<blockquote class="blockquote">
<p>On the next page (<a href="./OccMods_WithCovariates.html">Occupancy Models: Covariates</a>), I’ll explain how to include environmental or site-level covariates, like distance to a road or release pen. For now, we’ll leave those out to keep things simple.</p>
</blockquote>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spOccupancy)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">simOcc</span>(<span class="at">J.x =</span> <span class="dv">5</span>, <span class="at">J.y =</span> <span class="dv">2</span>, <span class="at">n.rep =</span> <span class="fu">rep</span>(<span class="dv">3</span>, <span class="at">times =</span> <span class="dv">10</span>), <span class="at">beta =</span> <span class="fu">c</span>(<span class="dv">1</span>), <span class="at">alpha =</span> <span class="fu">c</span>(<span class="dv">0</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> dat<span class="sc">$</span>y</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3]
 [1,]    0    1    0
 [2,]    0    0    1
 [3,]    0    0    0
 [4,]    0    0    0
 [5,]    0    1    1
 [6,]    1    1    0
 [7,]    1    0    1
 [8,]    0    0    0
 [9,]    0    1    0
[10,]    0    1    1</code></pre>
</div>
</div>
<p>Each column represents a survey occasion (we have three here), and each row corresponds to a site (ten total). Your dataset might have more or fewer rows/columns depending on your study, but the core format, called a <em>detection history matrix</em> or just <em>detection matrix</em>, will look something like this.</p>
<p>Let’s do the same thing that we did above, but with this more sensibly simulated dataset.</p>
<ol type="1">
<li><p>In sites 3, 4, and 8, we never detect elephants. With no further information, we can’t say whether that’s because they were truly absent, or present but undetected.</p></li>
<li><p>In sites 1, 2, 5, 6, 7, 9, and 10, we see elephants at least once, so we know for sure that they are present there.</p></li>
<li><p>In site 5, the detection history is <code>0</code>, <code>1</code>, <code>1</code>. So, if elephants were present for all surveys (closure assumed), we detected them in 2 out of 3 attempts, suggesting an estimated detection probability of about 66%.</p></li>
</ol>
<p>Armed with this 66% detection probability, we can ask: <em>If elephants were present at a site, what’s the chance we’d fail to detect them on all surveys?</em></p>
<p>Let’s assume elephants were present at site 3. The probability of <strong>not detecting</strong> them on a single day is:</p>
<p><span class="math display">\[1-0.66 = 0.34\]</span></p>
<p>Then the probability of failing to detect them three days in a row is:</p>
<p><span class="math display">\[0.34 \times 0.34 \times 0.34 = 0.34^3 = 0.04 or 4\%\]</span></p>
<p>So, if elephants <em>were</em> present, there’s only a 4% chance we’d miss them all three times. That’s pretty unlikely, so we might reasonably infer that site 3 was truly unoccupied.</p>
<p>And since this is simulated data, we can check the truth; we know whether elephants were really there or not.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>z[<span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>We see that elephants were absent in site 5. The output above should read <code>[1] 0</code>, which means absence. Our guess was correct. It was more likely that elephants were simply not there, rather than being present and somehow undetected every time.</p>
<p>This is essentially how occupancy models work. But instead of using a single site and a rough estimate of detection probability, we use all of our data across all sites and surveys. The occupancy model then estimates both the probability that a site is occupied and the probability of detecting the species when it is present.</p>
</section>
<section id="data-preparation" class="level1">
<h1>Data preparation</h1>
<p>Before getting to running a fancy model, we need to get our dataset organised in a format that works for <code>spOccupancy</code>. Unlike linear models or GLMs, which typically use a simple <code>data.frame</code> to supply the data, <code>spOccupancy</code> expects a <code>list</code> object. This list can (and often will) contain <em>multiple</em> datasets and nested lists.</p>
<p>For the basic model we’ll fit below, we only need to include the <em>detection history matrix</em> - the one we used above. We’ll store this in a list called <code>etosha</code>.</p>
<p>So at this stage, we’re simply placing our existing <em>detection history matrix</em> into a list. It might seem like an unnecessary step now, but it becomes essential when we expand to more complex models with covariates, spatial structure, or hierarchical components.</p>
<p>Here’s the detection history matrix again, which we’ll use as input:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3]
 [1,]    0    1    0
 [2,]    0    0    1
 [3,]    0    0    0
 [4,]    0    0    0
 [5,]    0    1    1
 [6,]    1    1    0
 [7,]    1    0    1
 [8,]    0    0    0
 [9,]    0    1    0
[10,]    0    1    1</code></pre>
</div>
</div>
<p>Creating the <code>etosha</code> list is actually quite straightforward. We use the <code>list()</code> function in R to build the list and include only our detection history matrix (for now).</p>
<p>In this example, the detection data is stored as <code>dat$y</code> (since it was simulated), and we’ll assign that to an element called <code>y</code> inside our new list. By convention we call it <code>y</code> to match the notation from our model equations above.</p>
<blockquote class="blockquote">
<p>An important note, even though I’m using <code>dat$y</code> in the code here, for your own data, you will most likely have a single dataset that you would load in with e.g.&nbsp;<code>read.csv()</code>.</p>
</blockquote>
<p>If you want to see the code, click the <code>Code</code> button to the left.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>etosha <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> dat<span class="sc">$</span>y</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="fitting-the-model" class="level1">
<h1>Fitting the model</h1>
<p>Below we’re going to fit the simplest version of an occupancy model that we can, specifically:</p>
<p><span class="math display">\[z_i \sim Bernoulli(\psi_i)\\\]</span></p>
<p><span class="math display">\[logit(\psi_i) = \beta_0\\\]</span></p>
<p><span class="math display">\[y_{i,j} \sim Bernoulli(p_{i,j} \times z_i)\\\]</span></p>
<p><span class="math display">\[logit(p_{i,j}) = \alpha_0\]</span></p>
<p>This version of the model only has two average probabilities. One for the average probability that elephants occupy a site (<span class="math inline">\(\beta_0\)</span>, which is fit on the <em>logit</em> link function), and another for the average probability of detecting elephants <em>if</em> they are present (<span class="math inline">\(\alpha_0\)</span>, also fit on the <em>logit</em> link function).</p>
<p>The model is not fit using the so-called <em>frequentist framework</em>. Instead, it uses the <em>Bayesian</em> framework. I’ll gloss over what frequentist and Bayesian mean (and how they differ) for now, except to note that maybe 95% (<span class="math inline">\(\leftarrow\)</span> lousy stats joke) of scientists use the frequentist framework. Not by coincidence, it’s also the framework most commonly taught to students (which is partly why it’s so widely used).</p>
<p>For your future, keep in mind that many employers, rightly or wrongly, see Bayesian statistics as fancier and more sophisticated. It’s something worth including in your CV if you apply for quantitative jobs or PhDs.</p>
<p>The code below uses the <code>PGOcc()</code> function from the <code>spOccupancy</code> package to fit a single species, single season occupancy model with no explanatory variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">PGOcc</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The state model (i.e. what % that elephants are present?)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ~ 1 means we want an intercept only model (no covariates)</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">occ.formula =</span> <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The observation model (i.e. what % that we see elephants if present?)</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ~ 1 means the same as above - intercept only</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">det.formula =</span> <span class="sc">~</span><span class="dv">1</span>, </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Our carefully formatted dataset</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> etosha, </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Details to get the machinery to run that we'll ignore for now</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.chains =</span> <span class="dv">4</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.samples =</span> <span class="dv">2000</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.burn =</span> <span class="dv">200</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Having fit the model, we can inspect the parameter estimates:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
PGOcc(occ.formula = ~1, det.formula = ~1, data = etosha, n.samples = 2000, 
    verbose = FALSE, n.burn = 200, n.chains = 4)

Samples per Chain: 2000
Burn-in: 200
Thinning Rate: 1
Number of Chains: 4
Total Posterior Samples: 7200
Run Time (min): 0.0025

Occurrence (logit scale): 
              Mean     SD    2.5%    50%  97.5%   Rhat  ESS
(Intercept) 1.4601 0.9914 -0.1904 1.3426 3.7274 1.0065 1576

Detection (logit scale): 
               Mean     SD    2.5%     50%  97.5%   Rhat  ESS
(Intercept) -0.1952 0.4643 -1.0869 -0.2025 0.7266 1.0039 3274</code></pre>
</div>
</div>
<p>There’s a lot of information in this summary, but we only really care about a few things.</p>
<ul>
<li><p><code>Occurrence (logit scale)</code>. This refers to the state model, which estimates the probability that an elephant is present at any given site.</p></li>
<li><p><code>Detection (logit scale)</code>. This refers to the observation model, which estimates the probability that an elephant is detected in any given survey, assuming they were present.</p></li>
<li><p>The <code>(Intercept)</code> rows contains all the information on the intercept for the respective model. Since we only included an intercept in both models, this is the only row for both the state and observation models.</p></li>
<li><p><code>Mean</code> is the mean of the <em>posterior</em>. This is Bayesian terminology for the distribution of the parameter estimate. (It’s a bit more complicated than that, but we’ll return to Bayesian ideas later.)</p></li>
<li><p><code>SD</code> is the standard deviation of the posterior.</p></li>
<li><p><code>2.5%</code> is the lower bound of the 95% <em>credible interval</em>. This is not a confidence interval, but for now you can think of it as similar.</p></li>
<li><p><code>50%</code> is the median of the posterior.</p></li>
<li><p><code>97.5%</code> is the upper bound of the 95% credible interval.</p></li>
<li><p><code>Rhat</code> is likely new to you. It helps assess whether the model had any issues estimating the posterior. If <code>Rhat</code> is close to 1, it suggests no issues were detected. (Note: this does not guarantee the model is correct, only that it appears stable.) If <code>Rhat</code> is higher than about 1.1, the model may not have converged properly and might need to be adjusted.</p></li>
<li><p><code>ESS</code> stands for <em>Effective Sample Size</em>. This is another Bayesian diagnostic. For now, we want this value to be in the hundreds or ideally thousands. A low ESS suggests estimation problems and might also require model adjustments.</p></li>
</ul>
<p>In our case, everything looks fine. The <code>Rhat</code> values are close to 1 and the <code>ESS</code> values are all in the thousands. We can now move on to interpreting the results biologically.</p>
</section>
<section id="interpreting-the-results" class="level1">
<h1>Interpreting the results</h1>
<p>So what do our results mean?</p>
<p>For the state model (labelled <code>Occurrence</code> in the <code>spOccupancy</code> output), the estimated mean is 1.4601. But we would expect this to be a probability, right? Remember, we are fitting a Bernoulli GLM with a logit link. That means 1.4601 is on the <em>logit</em> scale.</p>
<p>We can convert this logit value to a probability using the same inverse logit function we used earlier.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(<span class="fl">1.4601</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.811548</code></pre>
</div>
</div>
<p>When we do that, we get a value of approximately 0.81, or 81%. So, the model estimates there is about an 80% chance that any given site is occupied by elephants.</p>
<p>Now compare that to the observed data. In our detection history, we only saw elephants in 70% of the sites. That might seem inconsistent at first, but this is exactly where the detection part of the model helps us. Because we do not have perfect detection, we expect the <em>true</em> occupancy rate to be higher than what the raw data suggests.</p>
<p>What about detection probability?</p>
<p>The mean of the intercept for detection is estimated (also on the logit scale) as -0.1952.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">0.1952</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4513544</code></pre>
</div>
</div>
<p>Converting that to a probability gives us about 45%. So, on average, if an elephant is present at a site, we have about a 45% chance of detecting it during any one survey.</p>
<p>If our detection probability is 45%, then the chance of missing an elephant on all three visits to a site is:</p>
<p><span class="math display">\[
(1 - 0.45)^3 = 0.55^3 = 0.17 = 17\%
\]</span></p>
<p>That is not a huge chance, but it is not trivial either. In other words, even when elephants are present, there is a meaningful chance we might not see them at all in the data.</p>
<p>The key takeaway is this: detection probability is not 100%. That single fact makes the Bernoulli GLM we started with right at the start of this page inappropriate. Because it ignores imperfect detection, it produces unreliable estimates. The occupancy model, by contrast, accounts for detection error and gives us a more trustworthy result.</p>
</section>
<section id="what-next" class="level1">
<h1>What next?</h1>
<p>There are three big elements this document has not yet covered.</p>
<section id="including-covariates" class="level3">
<h3 class="anchored" data-anchor-id="including-covariates">1. Including covariates</h3>
<p>Just like in the modelling you did in BI3010, we can add covariates that we believe influence <em>either</em> the <em>state model</em> (why elephants are present) or the <em>detection model</em> (how likely we are to see them).</p>
<p>Do you think rainfall affects the likelihood of detecting elephants? Then include rainfall as a covariate in the detection model. Do you think distance to water affects where elephants choose to be? Then include that in the state model. This lets us link occupancy and detection to real ecological or observational factors.</p>
</section>
<section id="bayesian-statistics" class="level3">
<h3 class="anchored" data-anchor-id="bayesian-statistics">2. Bayesian statistics</h3>
<p>Very simply, Bayesian statistics allows us to include our prior understanding of the world into the model. For example, we might believe that a reasonable range for the probability of elephant presence is between 20% and 90%. That is, we don’t think it is likely that <em>none</em> of the sites are occupied, and we also don’t believe <em>all</em> of them are.</p>
<p>These informed guesses are formally called <em>priors</em>. Priors are the foundation of Bayesian inference and do not exist in frequentist statistics. They allow us to combine prior knowledge with the data we collect to produce more informed estimates.</p>
</section>
<section id="spatial-autocorrelation" class="level3">
<h3 class="anchored" data-anchor-id="spatial-autocorrelation">3. Spatial autocorrelation</h3>
<p>Imagine one site is an elephant utopia. It has everything an elephant could ever want and is almost certainly occupied. Now consider a nearby site that is less ideal. On its own, we might expect a lower probability of occupancy. But because it is close to elephant utopia, it is more likely to be occupied than its local features alone would suggest.</p>
<p>This is an example of <strong>spatial autocorrelation</strong>. The occupancy of one site can influence the occupancy of nearby sites, depending on how close they are. If we ignore spatial autocorrelation, we risk drawing misleading conclusions. For example, we might falsely assume that the non-utopian site is attractive to elephants when in fact, its occupancy is driven by its proximity to a better site.</p>
<p>Failing to account for spatial structure can lead to flawed inference. Fortunately, occupancy models can be extended to handle this, and the <code>spOccupancy</code> package is designed with this in mind.</p>
</section>
</section>
<section id="lecture-recording" class="level1">
<h1>Lecture recording</h1>
<p>Below is an old recording of a lecture (from during the COVID lockdown) I gave that covers some of these ideas (in slightly less detail).</p>
<iframe src="https://abdn.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=3a68620b-f38d-467e-b791-acb701020d5e" width="720" height="405" allowfullscreen="">
</iframe>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>