{
  "hash": "6e9e3edd5fdac1e4364e360da604e344",
  "result": {
    "markdown": "---\ntitle: \"Including Covariates in Occupancy Models\"\nauthor: \"Deon Roos\"\ndate: \"2025-05-01\"\nformat:\n  html:\n    theme: flatly\n    highlight-style: monochrome\n    code-fold: true\n    toc: true\n    toc-depth: 2\n    toc-location: right\n---\n\n\nOn this page, we'll begin expanding on the intercept-only occupancy model we fit in *Occupancy Models: The basics* and begin the process of injecting some biology into the `etosha` elephant occupancy model.\n\nAs before, we'll be using `spOccupancy` to fit the occupancy model. In addition, I'm also using `ggplot2` and `patchwork` (which allows you to stich ggplots togeher) for visualisations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(spOccupancy)\nlibrary(ggplot2)\nlibrary(patchwork)\n```\n:::\n\n\n# The theory\n\nOn the previous page we went through a simple example to get a sense of how occupancy models work. We're now going to begin the process of slowly increasing the complexity. To start, we're going to need to include covariates (also called *explanatory variables* or *independent variables* or a wide variety of other names - terminology in statistics is a mess).\n\nLet's revisit our simple occupancy model:\n\n$$\nz_i \\sim \\text{Bernoulli}(\\psi_i)  \\tag{State Stochastic}\n$$\n\n$$\nlogit(\\psi_i) = \\beta_0\\\\  \\tag{State Deterministic}\n$$\n\n$$\ny_{i,j} \\sim Bernoulli(p_{i,j} \\times z_i)\\\\  \\tag{Observation Stochastic}\n$$\n\n$$\nlogit(p_{i,j}) = \\alpha_0  \\tag{Observation Deterministic}\n$$\n\nI've added some tags to the left to help us keep track of each part. Remember that here *stochastic* means \"the part of the model that deals with randomness\", and *deterministic* means \"the part of the model that deals with why something happens\". In this occupancy model, the State formulae represent why a species is present at a site or not, and the Observation formulae represent if the species is detected or not.\n\nWhat we're going to do in this section is to add in covariates to the deterministic parts (why something happens), starting with the observation model.\n\nThe first thing to I want to remind you of is that $y$ is indexed by both $i$ and $j$, where $i$ was the site and $j$ was the survey. That $j$ is important because it allows us to specify covariates that vary not just by site (e.g. site 1 has 20 trees while site 2 has 10 trees) but by survey as well (e.g. on survey 1 in site 1, the temperature was 20 degrees, 15 degrees in survey 2 and 5 degrees in survey 3). This means that anything that was different in one survey to the next can be accounted for and included in the model (so long as we can measure and record it).\n\nSpecifically, these *survey varying covariates* are features that we think may have made us (or whoever or whatever collected the data) to be more or less effective. Using cameras? Well maybe the presence of fog has a big impact on how likely we are to detect elephants. Doing surveys yourself? Well maybe the hour of day that you did the survey had a big impact. The point is, we can include these variables that deal with differences in detection probability.\n\n![A photo taken after some unseen animal triggered the motion sensor on a foggy day.](images/fog.jpg)\n\nI'll simulate a new dataset (with a bit more data for us to work with - 64 sites surveyed 3 times each) to show this off. I'll include a the detection covariate in this case, which is rainfall, but note that the values for rainfall will be centred on zero (don't worry about this - just treat it as the larger `rain` is, the more rain there was).\n\nHere's what the data looks like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ndat <- simOcc(J.x = 8, \n              J.y = 8, \n              n.rep = rep(3, times = 8 * 8), \n              beta = c(1), \n              alpha = c(-2, 0.5))\nobs <- dat$y\ndet_cov <- dat$X.p[,,2]\ndf <- data.frame(\n  survey = rep(1:3, each = 64),\n  cov = c(det_cov[,1], det_cov[,2], det_cov[,3]),\n  y = c(obs[,1], obs[,2], obs[,3])\n)\n\np1 <- ggplot(df) +\n  geom_boxplot(aes(x = factor(survey), y = cov)) +\n  geom_jitter(aes(x = factor(survey), y = cov),\n              width = 0.2, height = 0) +\n  labs(x = \"Survey\", y = \"Rainfall\") +\n  theme_minimal()\n\np2 <- ggplot(df) +\n  geom_jitter(aes(y = factor(y), x = cov),\n              alpha = 0.4, width = 0, height = 0.1) +\n  labs(x = \"Rainfall\", y = \"Elephant detection\") +\n  theme_minimal()\n\nobs_long <- as.data.frame(obs)\ncolnames(obs_long) <- paste0(\"Survey_\", 1:ncol(obs_long))\nobs_long$Site <- 1:nrow(obs_long)\n\nlibrary(tidyr)\nobs_long <- pivot_longer(obs_long, \n                         cols = starts_with(\"Survey\"), \n                         names_to = \"Survey\", \n                         values_to = \"Detection\")\n\nobs_long$Survey <- factor(obs_long$Survey, levels = paste0(\"Survey_\", 1:ncol(obs)))\nobs_long$Detection <- factor(obs_long$Detection, levels = c(1, 0), labels = c(\"Detection\", \"No detection\"))\n\n p3 <- ggplot(obs_long, aes(x = Site, y = Survey, fill = Detection)) +\n  geom_tile(color = \"white\") +\n  scale_fill_manual(values = c(\"Detection\" = \"darkgreen\", \"No detection\" = \"lightgrey\")) +\n  labs(x = \"Site\", y = \"Survey\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n\ndesign <- \"\nAB\nAB\nCC\n\"\n\np1 + p2 + p3 + plot_annotation(tag_levels = \"A\", tag_suffix = \")\") + plot_layout(design = design)\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n**A)** shows the amount of rainfall over each survey. Each point represents a site in a given survey. **B)** shows the amount of rainfall against whether or not an elephant was detected. **C)** shows the detection history, where detections of elephants are coloured green and no detection is coloured grey.\n\nNotice anything? In **A)** we can see that in each survey, there's a lot of variation across the 64 sites in how much rainfall there was; maybe peaking in survey 2. In **B)**, it looks like it might be more likely that we detect elephants more often when there's more rainfall. While **C)** shows that most of the time we only detect elephants in one survey then never again (remember the assumption of closure? we assume that whenever we detect an elephant, then they were present in all other surveys at that site).\n\nBased on **B)** how confident are you that there's an influence on rain on the detection probability of elephants? If you're confident there is, then how strong do you think it is? Can you say *exactly* how strong is it?\n\nThere's no way you can answer those questions. That's where we need stats. So let's add in rainfall to our model. I'll recycle the code from the previous document and include rainfall. Here's how we do that.\n\n## Data preparation\n\nJust like in the previous page, we need to include our different datasets into a `list`. If you're still not sure what a `list` is in `R`, think of it like a folder on your computer. You can add lots of different files to a folder (and any type of file), but they're all \"tied\" together by being within the same folder. That's the same as a `list` in `R`.\n\nHere, I'm going to do something seemingly strange. I'm going to create a `list` and include this into our `etosha` `list`. A list within a list. The reason is that we might have more than one detection covariate, so having a list, though redundant here, will make adding additional variables easier in the future.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note you wouldn't need to do the dat$X.p[,,2] bit\n# That's just because the data is simulated.\ndet.covs <- list(rain = dat$X.p[,,2])\n\netosha <- list(\n  y = dat$y,\n  det.covs = det.covs\n)\n```\n:::\n\n\nAnd we're good to go on to the modelling.\n\n## Fitting the model\n\nA few things to note in the `R` code;\n\n-   `occ.formula = ~ 1` is the equivalent to $logit(\\psi_{i,j}) = \\beta_0$\n\n    -   I.e. an intercept only occupancy model, meaning we are not including any covariates for the probability that a site is occupied.\n\n-   `det.formula = ~ rain` is the equivalent to $logit(p_i) = \\alpha_0 + \\alpha_1 \\times Rain_i$\n\n    -   I.e. we have both an intercept and slope given we have included rain in the model.\n\n-   We specify that all data is contained in the list (i.e. \"folder\") called `etosha`.\n\n-   The remainder of the arguments (e.g. `n.chains`) can be ignored for now.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- PGOcc(\n  # The state model (i.e. what % that elephants are present?)\n  # ~ 1 means we want an intercept only model (no covariates)\n  occ.formula = ~ 1, \n  # The observation model (i.e. what % that we see elephants if present?)\n  det.formula = ~ rain, \n  # Our carefully formatted dataset\n  data = etosha, \n  \n  # Details to get the machinery to run that we'll ignore for now\n  n.chains = 4,\n  n.samples = 2000,\n  n.burn = 200,\n  verbose = FALSE)\n```\n:::\n\n\n## Interpreting\n\nHaving now fit the model to the data, we can see what we've learnt:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nPGOcc(occ.formula = ~1, det.formula = ~rain, data = etosha, n.samples = 2000, \n    verbose = FALSE, n.burn = 200, n.chains = 4)\n\nSamples per Chain: 2000\nBurn-in: 200\nThinning Rate: 1\nNumber of Chains: 4\nTotal Posterior Samples: 7200\nRun Time (min): 0.018\n\nOccurrence (logit scale): \n              Mean     SD   2.5%   50%  97.5%   Rhat ESS\n(Intercept) 1.8753 0.9465 0.3078 1.772 4.0465 1.0516 349\n\nDetection (logit scale): \n               Mean     SD    2.5%     50%   97.5%   Rhat  ESS\n(Intercept) -1.8872 0.2946 -2.4610 -1.8939 -1.2939 1.0165 1038\nrain         0.6930 0.2384  0.2328  0.6877  1.1801 1.0025 2604\n```\n:::\n:::\n\n\nCompared to the model on the previous page we now have additional information for `Detection (logit scale)`; we have both an `(Intercept)` and `rain`. These are $\\alpha_0$ and $\\alpha_1$ from our detection model ($logit(p_i) = \\alpha_0 + \\alpha_1 \\times Rain_i$). If we really wanted to, we could now replace the parameter labels (e.g. the $\\alpha$s and $\\beta$s) with their now estimated values which would look like (rounding the estimates to two decimal points arbitrarily):\n\n$$z_i \\sim Bernoulli(\\psi_i)\\\\  \\tag{State Stochastic}$$\n\n$$\nlogit(\\psi_i) = 1.88\\\\  \\tag{State Deterministic}\n$$\n\n$$\ny_{i,j} \\sim Bernoulli(p_{i,j} \\times z_i)\\\\  \\tag{Observation Stochastic}\n$$\n\n$$\nlogit(p_{i,j}) = -1.89 + 0.69 \\times Rain_i  \\tag{Observation Deterministic}\n$$\n\nWith this, we can swap out $Rain$ in the *Observation Deterministic* equation for any value of rain that we might be interested in, to see how it changes our estimated detection probability. For example, let's see what happens when $Rain = 1$ (equivalent to lots of rain based on how I simulated `rain`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n-1.89 + 0.69 * 1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.2\n```\n:::\n:::\n\n\nOur logit value is -1.2. How do we get that into probabilities that we can actually understand? Backtransform out of logit using `plogis()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplogis(-1.89 + 0.69 * 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2314752\n```\n:::\n:::\n\n\nAnd we get a ca. 23% chance to detect an elephant when $Rain = 1$. What about when $Rain = 0$ (equivalent to medium rain)? Well, we can do that easily enough now that we know thew general steps:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplogis(-1.89 + 0.69 * 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1312445\n```\n:::\n:::\n\n\nWhen $Rain = 0$, we predict a ca. 13% chance to detect elephants.\n\nThis approach, whereby we make a prediction for a specific value of $Rain$ can be extended into making multiple predictions at once, such that we can then draw a line through them. Here's how we'd do that.\n\n## Plot predicted relationships\n\nWe start by creating a sequence of $Rain$ values, rather than doing one a time like we did above. Here we use the `seq()` function to create a sequence, which will range from the minimum $Rain$ value to the maximum within our dataset. The number of values that we want in this sequence is specified as 20 but we can choose any value here - we just need enough that the line is drawn \"accurately\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain <- seq(from = min(det.covs$rain),\n            to = max(det.covs$rain),\n            length.out = 20)\n\nrain\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] -2.71815687 -2.44127881 -2.16440076 -1.88752271 -1.61064465 -1.33376660\n [7] -1.05688855 -0.78001049 -0.50313244 -0.22625439  0.05062367  0.32750172\n[13]  0.60437977  0.88125783  1.15813588  1.43501393  1.71189199  1.98877004\n[19]  2.26564809  2.54252615\n```\n:::\n:::\n\n\nNow we have our values, we don't want to manually enter each value into our equation. Instead we can use the fact that `R` works with vectors (i.e. columns of data) to do this quickly and easily:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred <- plogis(-1.89 + 0.69 * rain)\npred\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 0.02263134 0.02726568 0.03281714 0.03945308 0.04736516 0.05677017\n [7] 0.06790956 0.08104689 0.09646267 0.11444547 0.13527876 0.15922259\n[13] 0.18649040 0.21722152 0.25145143 0.28908330 0.32986526 0.37337882\n[19] 0.41904309 0.46613767\n```\n:::\n:::\n\n\nNow for each value of rain, we have the predicted probability of detecting an elephant. Useful but you wouldn't want to throw these two columns at your audience/reader and expect them to make sense of it. It'd be better if we include these in a figure.\n\nTo do so, we'll combine both columns into a single dataset and plot using `ggplot2`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(\n  pred,\n  rain\n)\n\nggplot(df) +\n  geom_line(aes(x = rain, y = pred))\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nFrom this figure it now appears much more intuitive that increasing rain makes elephants easier to detect. We can do a little \"tidying\" of the figure to make it more visually pleasing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df) +\n  geom_line(aes(x = rain, y = pred)) +\n  scale_y_continuous(labels = scales::percent,\n                     limits = c(0,1)) +\n  theme_minimal() +\n  labs(x = \"Mean rainfall\",\n       y = \"Predicted detection\\nprobability of elephants\")\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nBased on our figure, we'd now be able to make some biological inference. From what we see in our figure, we have evidence that elephants are easier to spot when it rains. If we were writing this as a paper, we might discuss why that was the case. However (and this is important) we should have really considered this *before* we did the analysis. The risk of making sense of this now is that we rationalise something that's actually stupid. This is something called HARKing, or Hypothesising After the Results are Known and it's a form of scientific fraud. Keep in mind, this is simulated data where the stakes are low. My goal here is to explain the methods to you. With real analysis, we need to be more thorough and responsible - so make sure you have your hypotheses before you do your analysis!\n\n## Uncertainty\n\nThe above figure is a good start but we're missing any measure of uncertainty. If we were doing frequentist statistics, we would use 95% confidence intervals but these are exclusively frequentist. There are no 95% confidence intervals when we use the Bayesian statistical framework. Instead we have *credible intervals*. I'll explain the Bayesian framework in a subsequent workflow but for now here is the formal definition of a **credible** interval:\n\n> There is a 95% probability that the **True** parameter value lies within the interval range, given the data and model.\n\nThis is in contrast with the frequentist confidence interval whose formal definition of a confidence interval is so bizarre and unintuitive that it's barely useful. 95% *credible intervals* are actually useful and work exactly the way people *think* frequentist intervals work. I'll explain how they work in a later page, so just trust me for now that they're *better*.\n\nBut how do we include these in the figure? Well, the model summary makes it easy to find the values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nPGOcc(occ.formula = ~1, det.formula = ~rain, data = etosha, n.samples = 2000, \n    verbose = FALSE, n.burn = 200, n.chains = 4)\n\nSamples per Chain: 2000\nBurn-in: 200\nThinning Rate: 1\nNumber of Chains: 4\nTotal Posterior Samples: 7200\nRun Time (min): 0.018\n\nOccurrence (logit scale): \n              Mean     SD   2.5%   50%  97.5%   Rhat ESS\n(Intercept) 1.8753 0.9465 0.3078 1.772 4.0465 1.0516 349\n\nDetection (logit scale): \n               Mean     SD    2.5%     50%   97.5%   Rhat  ESS\n(Intercept) -1.8872 0.2946 -2.4610 -1.8939 -1.2939 1.0165 1038\nrain         0.6930 0.2384  0.2328  0.6877  1.1801 1.0025 2604\n```\n:::\n:::\n\n\nThey're the `2.5%` and `97.5%` values in our summary table. So all we need to do is repeat the code we used to make our predictions, except now using these credible interval values to get our measure of uncertainty. Importantly, if you remember back to BI3010 where you had to multiplya parameters standard error by 1.96, we ***do not*** need to do that here. That's frequentist nonsense - we're fancy Bayesian scientists now.\n\nLet's do just that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf$low <- plogis(-2.4610 + 0.2328 * df$rain)\ndf$upp <- plogis(-1.2939 + 1.1801 * df$rain)\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         pred        rain        low        upp\n1  0.02263134 -2.71815687 0.04336427 0.01096960\n2  0.02726568 -2.44127881 0.04611831 0.01514457\n3  0.03281714 -2.16440076 0.04903828 0.02087495\n4  0.03945308 -1.88752271 0.05213304 0.02871039\n5  0.04736516 -1.61064465 0.05541172 0.03936862\n6  0.05677017 -1.33376660 0.05888379 0.05376451\n7  0.06790956 -1.05688855 0.06255900 0.07302436\n8  0.08104689 -0.78001049 0.06644741 0.09846565\n9  0.09646267 -0.50313244 0.07055932 0.13151304\n10 0.11444547 -0.22625439 0.07490526 0.17351714\n11 0.13527876  0.05062367 0.07949599 0.22545433\n12 0.15922259  0.32750172 0.08434241 0.28752905\n13 0.18649040  0.60437977 0.08945559 0.35877811\n14 0.21722152  0.88125783 0.09484663 0.43685701\n15 0.25145143  1.15813588 0.10052670 0.51819600\n16 0.28908330  1.43501393 0.10650691 0.59858193\n17 0.32986526  1.71189199 0.11279825 0.67399363\n18 0.37337882  1.98877004 0.11941156 0.74135968\n19 0.41904309  2.26564809 0.12635738 0.79895748\n20 0.46613767  2.54252615 0.13364590 0.84638633\n```\n:::\n:::\n\n\nAnd we can add in our uncertainty using `geom_ribbon()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df) +\n  geom_line(aes(x = rain, y = pred)) +\n  geom_ribbon(aes(x = rain, ymin = low, ymax = upp),\n              alpha = 0.3) +\n  scale_y_continuous(labels = scales::percent,\n                     limits = c(0,1)) +\n  theme_minimal() +\n  labs(x = \"Mean rainfall\",\n       y = \"Predicted detection\\nprobability of elephants\")\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nWith that, we have a publication ready figure.\n\n# Multiple covariates\n\nLet's increase the complexity a bit and have the simulation include multiple covariates. We'll say that tree height and average temperature affect whether or not a site is occupied (elephants will like tall trees and cooler locations). We'll still have rain affect our detection probability, as above.\n\nA note here is that the covariates are still centered on zero. That's just the way the data is simulated but the data you collect does not need to be the same (so ignore the fact that we will have trees that are -1 m tall - the general idea doesn't change).\n\n> A technical note if you're interested. To create the figures below I need to do some tweaks to the data. The `df` object I create in the code below has one row per survey, with three surveys per site. Our occupancy covariates, `tree` and `temp` have just one value; these do not change from one survey to the next. If a tree is 3 m tall in survey one, then it'll still be 3 m tall in surveys two and three. That's why I \"cheat\" and replicate `tree` and `temp` three times each.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ndat <- simOcc(J.x = 8, \n              J.y = 8, \n              n.rep = rep(3, times = 8 * 8), \n              beta = c(1, -0.2, 0.3), \n              alpha = c(-2, 0.5))\nobs <- dat$y\ntemp <- dat$X[,2]\ntree <- dat$X[,3]\ndet_cov <- dat$X.p[,,2]\ndf <- data.frame(\n  survey = rep(1:3, each = 64),\n  cov = c(det_cov[,1], det_cov[,2], det_cov[,3]),\n  tree = rep(tree, times = 3),\n  temp = rep(temp, times = 3),\n  y = c(obs[,1], obs[,2], obs[,3])\n)\n\np1 <- ggplot(df) +\n  geom_histogram(aes(x = temp)) +\n  labs(y = \"Count\", x = \"Temperature\") +\n  theme_minimal()\n\np2 <- ggplot(df) +\n  geom_jitter(aes(y = factor(y), x = temp),\n              alpha = 0.4, width = 0, height = 0.1) +\n  labs(x = \"Temperature\", y = \"Elephant\\ndetection\") +\n  theme_minimal()\n\np3 <- ggplot(df) +\n  geom_histogram(aes(x = tree)) +\n  labs(x = \"Tree height\", y = \"Count\") +\n  theme_minimal()\n\np4 <- ggplot(df) +\n  geom_jitter(aes(y = factor(y), x = tree),\n              alpha = 0.4, width = 0, height = 0.1) +\n  labs(x = \"Tree\", y = \"Elephant\\ndetection\") +\n  theme_minimal()\n\np5 <- ggplot(df) +\n  geom_histogram(aes(x = cov)) +\n  labs(x = \"Rain\", y = \"Count\") +\n  theme_minimal()\n\np6 <- ggplot(df) +\n  geom_jitter(aes(y = factor(y), x = tree),\n              alpha = 0.4, width = 0, height = 0.1) +\n  labs(x = \"Rain\", y = \"Elephant\\ndetection\") +\n  theme_minimal()\n\nobs_long <- as.data.frame(obs)\ncolnames(obs_long) <- paste0(\"Survey_\", 1:ncol(obs_long))\nobs_long$Site <- 1:nrow(obs_long)\n\nobs_long <- pivot_longer(obs_long, \n                         cols = starts_with(\"Survey\"), \n                         names_to = \"Survey\", \n                         values_to = \"Detection\")\n\nobs_long$Survey <- factor(obs_long$Survey, levels = paste0(\"Survey_\", 1:ncol(obs)))\nobs_long$Detection <- factor(obs_long$Detection, levels = c(1, 0), labels = c(\"Detection\", \"No detection\"))\n\n p7 <- ggplot(obs_long, aes(x = Site, y = Survey, fill = Detection)) +\n  geom_tile(color = \"white\") +\n  scale_fill_manual(values = c(\"Detection\" = \"darkgreen\", \"No detection\" = \"lightgrey\")) +\n  labs(x = \"Site\", y = \"Survey\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n\n design <- \"\n AB\n AB\n CD\n CD\n EF\n EF\n GG\n GG\n \"\n \np1 + p2 + p3 + p4 + p5 + p6 + p7 +\n   plot_annotation(tag_levels = \"A\", tag_suffix = \")\") + \n   plot_layout(design = design)\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-16-1.png){width=1152}\n:::\n:::\n\n\nThere are two things worth highlighting from the above figures. Firstly, based on how we \"measured\" and \"collected\" the data temperature and tree height in **A)**, **B)**, **C)** and **D)** do not change from one survey to the next. These are constant from one day to the next and will be used as *site covariates* in the model (i.e. variables which only change from one site to the next). *A small note here is that you can have site covariates that change in both surveys and sites, but I'm keeping things simple here*. Conversely, in **E)** and **F)** does vary from one survey to the next and between sites. We'll use this as a *survey covariate* in the model.\n\nSecondly, it becomes quite hard to see any clear pattern in the two right hand figures, **B)** and **D)**. Keep in mind that the zeros in *detections* are misleading. Some of the zeros are genuine, in that there were no elephants there, and `tree` and `temp` caused that (which I only know because the data is simulated in this case) but the other zeros are false negatives; The elephants were there, we just didn't see them.\n\nThis is why we need a model to figure out what the relationships are. We can no longer trust our eyes to see the pattern.\n\nSo let's get our data organised such that we can fit our model.\n\n## Data preparation\n\nAs before, we provide our *survey covariates* as a `list` but our site covariates can be supplied as a `dataframe`. Keep in mind, both of these are included in another `list`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Survey covariate\ndet.covs <- list(rain = dat$X.p[,,2])\n# Site covariates\nocc.covs <- data.frame(tree = tree, temp = temp)\netosha <- list(\n  y = dat$y, # Detection history\n  det.covs = det.covs,\n  occ.covs = occ.covs\n)\n```\n:::\n\n\n## Fitting the model\n\nThe core model we're going to fit is:\n\n$$z_i \\sim Bernoulli(\\psi_i)$$\n\n$$logit(\\psi_i) = \\beta_0 + \\beta_1 \\times Tree_i + \\beta_2 \\times Temp_i\\\\$$\n\n$$y_{i,j} \\sim Bernoulli(p_{i,j} \\times z_i)\\\\$$\n\n$$logit(p_{i,j}) = \\alpha_0 + \\alpha_1 \\times Rain_{i,j}$$\n\nThe main thing that I want to highlight here, other than having included $Tree$ and $Temp$ as effecting occupancy probability ($\\psi$), is that the subscripts are different.\n\nIn the deterministic part of the state model ($logit(\\psi_i) = \\beta_0 + \\beta_1 \\times Tree_i + \\beta_2 \\times Temp_i$) the variables are subscript by $i$, indicating that we have one value of $Tree$ or $Rain$ for each site $i$.\n\nBut in the deterministic part of the observation model ($logit(p_{i,j}) = \\alpha_0 + \\alpha_1 \\times Rain_{i,j}$) $Rain$ is subscript by both $i$ and $j$. That's because we have a different $Rain$ value for each survey $j$. This would be something we record every time we visit the site (or extract from some online source for each sampling period).\n\nKeep this in mind when you're collecting your own data. Variables that you think affect occupancy will (normally) have one value per site. Variables that you think affect detection will (generally) have one value per survey. But speak to me if you think you want to try something different.\n\nTo fit this is relatively straight forward. For the occupancy model, we write `occ.formula = ~ tree + temp`, and for the detection model we write `det.formula = ~ rain`, and let the machinery do it's thing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- PGOcc(\n  occ.formula = ~ tree + temp, \n  det.formula = ~ rain, \n  data = etosha, \n  \n  # Details to get the machinery to run that we'll ignore for now\n  n.chains = 4,\n  n.samples = 2000,\n  n.burn = 200,\n  verbose = FALSE)\n```\n:::\n\n\nOnce it's run, we can check the `summary()` to see what the parameters were estimated as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nPGOcc(occ.formula = ~tree + temp, det.formula = ~rain, data = etosha, \n    n.samples = 2000, verbose = FALSE, n.burn = 200, n.chains = 4)\n\nSamples per Chain: 2000\nBurn-in: 200\nThinning Rate: 1\nNumber of Chains: 4\nTotal Posterior Samples: 7200\nRun Time (min): 0.0182\n\nOccurrence (logit scale): \n               Mean     SD    2.5%     50%  97.5%   Rhat ESS\n(Intercept)  1.9515 1.0600  0.1862  1.8333 4.2716 1.0441 347\ntree         0.3649 1.2506 -2.0020  0.3180 2.8503 1.0383 293\ntemp        -1.1005 1.1484 -3.2573 -1.1617 1.3032 1.0452 277\n\nDetection (logit scale): \n               Mean     SD    2.5%     50%   97.5%   Rhat  ESS\n(Intercept) -1.8428 0.2636 -2.3606 -1.8424 -1.3199 1.0023 1404\nrain         0.1730 0.2214 -0.2499  0.1707  0.6115 1.0023 2983\n```\n:::\n:::\n\n\nWe see that `tree` has a positive effect on occupancy (0.3649) and `temp` has a negative effect (-1.1005). This is kind of good. These estimates are close to the values I used in the simulation - but they don't match up particularly well. Specifically, in the simulation `tree` was set to `0.3` but has been estimated as `0.37` (pretty close), while `temp` was set to `-0.2` but has been estimated as `-1.1` (kind of far away).\n\nSo we've got the general relationships reasonably well estimated but it's not perfectly accurate to the **True** value I used in the simulation. This is where having *credible intervals* is useful. Keep in mind that credible intervals are, correctly, interpreted as having a 95% chance of containing the \"True\" value (the True value here is what each parameter was set to in the simulation). For both `tree` and `temp` the True parameter value is indeed within the 95% credible intervals! Both 95% CI are wide, but that's good here! The model isn't entirely sure what the values are (partly because of sample size and the effects being subtle) and that is being conveyed to us! We're not deluding ourselves into thinking we have a perfect understanding when we don't!\n\nThere are some warning signs that the model might not be performing especially well. The first is that the `Rhat` values are getting uncomfortably large for the `Occurence` parameters. My personal rule of thumb is `Rhat` values close to 1.05 is where I get worried. None of our parameters are at 1.05 but they're close enough that I'm paying attention to them and want to see if I can fix the problem. We'll come back to `Rhat` values when we talk about *Bayesian* statistics.\n\nThe other warning sign is the `ESS` for the `Occurence` model are all \"low\". At least noticeably lower than the `Detection` model parameters. Again, the rule of thumb here is that we want hundreds or thousands of \"Effective Sample Size\", so we're technically OK but I'm still concerned. We'll also cover `ESS` later on.\n\nNow, to be clear, we ignored these issues with the first model we ran in this document, whereas here we're going to see if we can resolve this problem.\n\n## Resolving issues\n\nTo fully appreciate the solution will require a deeper understanding of Bayesian statistics. But for now, we're not going to cover this. Instead, I'll simply say that the \"machinery\" of Bayesian statistics revolves around giving a number of algorithms (called \"chains\") a number of guesses (called \"iterations\") to try and figure out the most likely values for our parameters.\n\nThe two metrics we used above, `Rhat` and `ESS`, both monitor these chains and iterations and let us know if they are *not in agreement* (`Rhat`) or when they haven't been well estimated (`ESS`). When `Rhat` values get high, and `ESS` values get low, it *can* suggest we need to give the algorithms more iterations (i.e. chances to intelligently guess).\n\nInevitably, the details are more complex than I can convey in two paragraphs but the general idea is there. If either number looks a bit worrying, it's relatively cheap and easy to just rerun the model with more iterations and see if that solves the problem.\n\nLet's do just that by increasing the number of iterations to 3000 per chain:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- PGOcc(\n  occ.formula = ~ tree + temp, \n  det.formula = ~ rain, \n  data = etosha, \n  \n  # We're using four chains/algorithms\n  n.chains = 4,\n  # We allow 3000 guesses (increased from 2000)\n  n.samples = 3000,\n  # We ignore the first 300 (increased from 200)\n  # We ignore them because we assume the algorithms are not particularly reliable\n  # in the first ca. 10% of guesses\n  n.burn = 300,\n  verbose = FALSE)\n```\n:::\n\n\nOnce run, we can check how well they ran:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nPGOcc(occ.formula = ~tree + temp, det.formula = ~rain, data = etosha, \n    n.samples = 3000, verbose = FALSE, n.burn = 300, n.chains = 4)\n\nSamples per Chain: 3000\nBurn-in: 300\nThinning Rate: 1\nNumber of Chains: 4\nTotal Posterior Samples: 10800\nRun Time (min): 0.0263\n\nOccurrence (logit scale): \n               Mean     SD    2.5%     50%  97.5%   Rhat ESS\n(Intercept)  1.9586 1.0113  0.1496  1.8785 4.0979 1.0061 533\ntree         0.3562 1.2971 -2.0341  0.3101 2.9698 1.0498 415\ntemp        -1.2475 1.0628 -3.3183 -1.2672 0.9406 1.0176 470\n\nDetection (logit scale): \n               Mean     SD    2.5%     50%   97.5%   Rhat  ESS\n(Intercept) -1.8461 0.2664 -2.3631 -1.8497 -1.3123 1.0014 1625\nrain         0.1791 0.2196 -0.2462  0.1772  0.6243 1.0016 4411\n```\n:::\n:::\n\n\nNow when we look at the `Rhat` and `ESS` values, we are doing better. Still not perfect but good enough for me to be happy that *by these two metrics alone* there's nothing to suggest the machinery is struggling and that the parameters are being estimated as robustly as possible.\n\n> Importantly, these are not the only metrics or tools available to us. We'll check out the other options in a later document.\n\nAs far as we can tell, for now, we can trust this model and move on to plotting the predicted relationships.\n\n## Plot predicted relationships\n\nPreviously, we made the predictions ourselves by \"hand\". This time, we're going to use the `predict()` function to do this for us to make life easier on ourselves. Importantly, the process is exactly the same;\n\n1.  Create a \"fake\" dataset with the covariate values we want to predict for.\n\n2.  Apply this fake data to our equation, with the now estimated parameter values, to generate the predictions. We'll make life easier for ourselves by using `predict()` rather than doing it by hand.\n\n3.  Convert from logit values to probabilities.\n\n4.  Plot the predicted probabilities against the fake covariate values to show the estimated relationship.\n\nRemember that occupancy models are really two $Bernoulli$ GLMs that speak to each other. When using `predict()` we need to specify which \"model\" we want to predict from.\n\nNormally, for a GLM I'd start by making a figure for `tree` height. Just like in BI3010, remember that when we have multiple explanatory variables in a model, to make the figure for one variable, we hold all others constant at some other value - often the median.\n\nHowever, for these models there are a few extra (annoying) things we need to do and for me to explain here. As a warning some of these get quite technical. It might be a good time to take a break and come back when you're fresh.\n\nWhenever you do tackle this next part, if you get confused, don't worry. We can talk this through in person.\n\n### Model matrix\n\nIn the code below I create something called a model matrix (`model.matrix()`). This is a way to turn our covariate data (like `tree` and `temp`) into the actual numbers and form used in the model. When we fit a model like `~ tree + temp`, `R` internally builds a matrix where each column represents a variable (or intercept), and each row is a combination of values at a site. This matrix is what the model uses to calculate predictions.\n\nWhen we use `predict()` with a fitted occupancy model, we must supply this design matrix (`X.0`) because it matches the structure the model expects, just like when we built it during fitting.\n\n### `qlogis` and `plogis`\n\nWhen we use `predict()` for our occupancy model, we get thousands of *posterior* draws (I'll explain this later but for now, think of these are different likely values the parameter could be) for each site's occupancy probability (i.e. these are already backtransformed out of logit values into probabilities for us).\n\nBut here's the subtle issue (and it is really, *really*, super subtle).\n\nIf we calculate the mean or credible intervals of these already backtransformed probabilities, it can sometimes end up looking distorted (e.g. it might look like it increases, peaks, then decreases). So to be safe:\n\n1.  We have to take our probabilities and turn them *back* into logit values (annoyingly) using `qlogis()`.\n2.  Then we calculate the mean and credible intervals.\n3.  Then we backtransform out of logit back into probabilities.\n\n### `apply()`\n\nWhen we summarise the *posterior*, we have one row per iteration (or guess) and one column per site. So to summarise, we need to take the mean across row (i.e. across all iterations) for each column. That's what the `apply()` function is doing in our code.\n\nHonestly, the code is more complex than I would like. I wish I could think of a simpler way to do it (and I might ask my wife, who's better at coding than me, to see if she can improve it) but this is the best I can do for now. Speak to me if you need help.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Create a new fake data frame for tree (hold temp at median)\nfake <- data.frame(\n  tree = seq(min(etosha$occ.covs$tree), max(etosha$occ.covs$tree), length.out = 100),\n  temp = median(etosha$occ.covs$temp)\n)\n\n# Step 2: Convert this into a model matrix\nX.0 <- model.matrix(~ tree + temp, data = fake)\n\n# Step 3: Predict occupancy from model matrix\npred_occ <- predict(fit, X.0 = X.0, type = \"occupancy\")\n\n# Step 4: Transform back into logit values\nlogit_psi_samples <- qlogis(pred_occ$psi.0.samples)\n\n# Step 5: Summarize the posteriors\nfake <- data.frame(\n  tree = fake$tree,\n  mean.psi = apply(logit_psi_samples, 2, mean),\n  lower = apply(logit_psi_samples, 2, function(x) quantile(x, 0.025)),\n  upper = apply(logit_psi_samples, 2, function(x) quantile(x, 0.975))\n)\n\n# Step 6: Backtransform into probabilities\nfake <- data.frame(\n  tree = fake$tree,\n  mean.psi = plogis(fake$mean.psi),\n  lower = plogis(fake$lower),\n  upper = plogis(fake$upper)\n)\n\n# Step 7: Plot\nggplot(fake, aes(x = tree, y = mean.psi)) +\n  geom_line() +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.3) +\n  labs(x = \"Tree height\", y = \"Occupancy probability (ψ)\") +\n  scale_y_continuous(labels = scales::percent) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nWe repeat this for `temp`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Create a new data frame for temp (hold tree at median)\nfake <- data.frame(\n  tree = median(etosha$occ.covs$tree),\n  temp = seq(min(etosha$occ.covs$temp), max(etosha$occ.covs$temp), length.out = 100)\n)\n\n# Step 2: Convert this into a model matrix\nX.0 <- model.matrix(~ tree + temp, data = fake)\n\n# Step 3: Predict occupancy from model matrix\npred_occ <- predict(fit, X.0 = X.0, type = \"occupancy\")\n\n# Step 4: Transform back into logit values\nlogit_psi_samples <- qlogis(pred_occ$psi.0.samples)\n\n# Step 5: Summarize the posteriors\nfake <- data.frame(\n  temp = fake$temp,\n  mean.psi = apply(logit_psi_samples, 2, mean),\n  lower = apply(logit_psi_samples, 2, function(x) quantile(x, 0.025)),\n  upper = apply(logit_psi_samples, 2, function(x) quantile(x, 0.975))\n)\n\n# Step 6: Backtransform into probabilities\nfake <- data.frame(\n  temp = fake$temp,\n  mean.psi = plogis(fake$mean.psi),\n  lower = plogis(fake$lower),\n  upper = plogis(fake$upper)\n)\n\n# Step 5: Plot\nggplot(fake, aes(x = temp, y = mean.psi)) +\n  geom_line() +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.3) +\n  labs(x = \"Temperature\", y = \"Occupancy probability (ψ)\") +\n  scale_y_continuous(labels = scales::percent) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nAnd finally for rain affecting our detection probability:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Create a new data frame for temp (hold tree at median)\nfake <- data.frame(\n  rain = seq(min(etosha$det.covs$rain), max(etosha$det.covs$rain), length.out = 100)\n)\n\n# Step 2: Convert this into a model matrix\nX.0 <- model.matrix(~ rain, data = fake)\n\n# Step 3: Predict occupancy from model matrix\npred_det <- predict(fit, X.0 = X.0, type = \"detection\")\n\n# Step 4: Transform back into logit values\nlogit_p_samples <- qlogis(pred_det$p.0.samples)\n\n# Step 5: Summarize the posteriors\nfake <- data.frame(\n  rain = fake$rain,\n  mean.p = apply(logit_p_samples, 2, mean),\n  lower = apply(logit_p_samples, 2, function(x) quantile(x, 0.025)),\n  upper = apply(logit_p_samples, 2, function(x) quantile(x, 0.975))\n)\n\n# Step 6: Backtransform into probabilities\nfake <- data.frame(\n  rain = fake$rain,\n  mean.p = plogis(fake$mean.p),\n  lower = plogis(fake$lower),\n  upper = plogis(fake$upper)\n)\n\n# Step 5: Plot\nggplot(fake, aes(x = rain, y = mean.p)) +\n  geom_line() +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.3) +\n  labs(x = \"Rainfall\", y = \"Detection probability (p)\") +\n  scale_y_continuous(labels = scales::percent) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](OccMods_WithCovariates_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n# How should I store my data?\n\nThe data storage for these models can seem a bit complicated at first. I would suggest you start off by having at least three datasets.\n\n## Dataset one\n\nThis is your detection history. Create an excel document, where each site (or camera) is on a row, and each survey period is a column. For the sake of argument, say that your sampling period is a 12 hour period, and you have three surveys at each location. Your excel should look something like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndh <- as.data.frame(dat$y)\ncolnames(dh) <- c(\"1\", \"2\", \"3\")\ndh\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   1 2 3\n1  0 0 0\n2  0 0 0\n3  0 0 0\n4  0 0 0\n5  0 0 0\n6  1 0 0\n7  0 0 0\n8  0 0 0\n9  0 1 1\n10 0 0 0\n11 0 0 0\n12 0 0 0\n13 0 0 0\n14 0 1 0\n15 0 0 1\n16 0 0 0\n17 0 0 0\n18 0 0 0\n19 0 0 0\n20 0 0 0\n21 0 0 0\n22 0 0 0\n23 0 0 0\n24 0 0 0\n25 0 0 1\n26 0 0 0\n27 0 0 1\n28 0 0 1\n29 0 1 0\n30 0 1 0\n31 0 0 0\n32 0 0 0\n33 1 0 0\n34 0 0 0\n35 1 0 0\n36 0 0 0\n37 0 0 0\n38 0 0 0\n39 1 0 0\n40 0 1 0\n41 0 0 0\n42 0 0 0\n43 1 0 0\n44 0 0 0\n45 0 0 0\n46 0 1 0\n47 0 0 1\n48 0 0 0\n49 0 0 0\n50 0 0 0\n51 0 0 0\n52 0 0 1\n53 0 0 0\n54 0 1 0\n55 0 1 0\n56 0 0 0\n57 0 0 0\n58 0 0 1\n59 0 0 0\n60 1 0 0\n61 0 0 0\n62 0 0 0\n63 0 0 0\n64 0 0 0\n```\n:::\n:::\n\n\n## Dataset two\n\nCreate another excel spreadsheet which will contain all of your site level covariates. This should be organised in the same order as your detection history dataset (above), such that if site 1 is top of your detection history spreadsheet, it should be top here as well. **THIS IS CRUCIAL - BE CAREFUL AND MAKE SURE THIS IS DONE CORRECTLY**.\n\nIf you are interested in distance to road, have that be in here. If you are interested in distance to nearest pen, include it here. Each covariate should be a column:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(road = round(rgamma(50, 1, 2), digits = 3), pen = round(rgamma(50, 2, 3), digits = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    road pen\n1  1.413 0.6\n2  0.365 0.4\n3  0.748 1.3\n4  0.028 1.5\n5  0.206 0.7\n6  0.486 0.8\n7  1.142 1.0\n8  0.316 0.2\n9  0.894 0.8\n10 1.180 0.5\n11 0.108 0.6\n12 0.036 0.1\n13 0.273 1.1\n14 1.003 0.5\n15 0.381 1.2\n16 0.275 0.5\n17 0.130 0.8\n18 1.046 0.2\n19 0.269 1.7\n20 0.914 0.5\n21 0.582 0.7\n22 1.695 0.4\n23 0.016 1.1\n24 0.032 1.8\n25 1.028 0.8\n26 0.039 0.2\n27 0.011 0.5\n28 0.601 0.9\n29 0.417 1.1\n30 0.600 1.8\n31 0.041 1.7\n32 0.013 0.2\n33 0.403 0.6\n34 0.018 0.4\n35 0.607 0.6\n36 0.277 0.2\n37 0.542 1.0\n38 0.123 0.1\n39 2.061 1.0\n40 1.840 0.5\n41 0.844 0.7\n42 0.023 1.3\n43 0.630 0.2\n44 0.212 0.3\n45 1.082 0.5\n46 0.032 0.5\n47 0.600 0.1\n48 0.690 0.5\n49 0.902 0.8\n50 0.491 0.3\n```\n:::\n:::\n\n\n## Dataset three (+)\n\nThe final dataset(s) contain your survey covariates, but **importantly**, you will need a new excel document for each survey covariate. So rather than having them all be together like in the site covariate speadsheet, here they'll look more like the detection history spreadsheet. Each row is a site and each column is a survey.\n\nSo if you were collecting data on light pollution you may have:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\"1\" = rnorm(50, 0, 1), \"2\" = rnorm(50, 1, 2), \"3\" = rnorm(50, -1, 1), check.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              1           2          3\n1  -2.080361780  3.31486871 -2.8792348\n2   1.193689080 -2.13245041 -0.9858541\n3   0.211096481  2.37159153 -2.5450504\n4  -0.804509302 -3.04365088  0.8123365\n5   1.242683769  1.98512256  0.5347766\n6   1.672370774 -0.86347112 -0.2739347\n7  -0.440110803  3.85228974 -1.2469645\n8   0.976970308  2.38465991  0.4144317\n9  -0.247292942  0.80483629 -2.0085643\n10  1.193662839  3.68860057 -0.7706345\n11  0.582106314  2.30774905 -0.7437351\n12 -0.212421470 -2.58811871  1.2101485\n13 -0.078270865  0.75188625 -0.5215089\n14  1.150840694 -0.18570337 -0.4912487\n15  0.575815240  1.98405202 -2.2456465\n16 -0.803085447  5.26614095 -1.3067553\n17 -0.003867098  0.83398723 -2.7237629\n18 -0.321186684  3.01674217 -1.7598763\n19  0.271986638  1.35000525 -1.1381807\n20 -0.129475777  1.40291064 -1.2840863\n21 -0.730130772  1.24783303 -0.7199777\n22  1.425657691 -0.16389270 -2.3773648\n23  1.165602885 -0.22977912 -1.5775563\n24  2.003211580 -3.12713915 -0.3410146\n25 -0.897058994  0.42866992 -0.6918805\n26  1.623248729  1.10980969  0.1850369\n27  3.082054870  0.59193629  0.3879526\n28  0.373362088  1.74746118 -1.5760394\n29 -0.138822386  0.67546058 -1.8727836\n30  0.888619009  7.36368823  0.1605281\n31  2.703796014  0.22554511 -2.8165337\n32 -0.338148148  0.48416927 -0.0640613\n33  1.038384187 -0.66954237 -1.2304174\n34 -0.344291247  4.28962590 -2.6571024\n35 -0.096846364 -0.05826384 -1.1676174\n36  0.302828810 -0.61888378 -1.3100760\n37  0.401658586  2.23291672 -1.7689837\n38 -0.093476762 -0.58908992  0.5388878\n39  0.026884978  0.87524859 -2.8523438\n40 -0.333933172  2.90140407 -2.1994696\n41  0.690967183  0.37129946 -0.7643009\n42  0.019305684  3.84486943 -0.4132671\n43 -0.357612499 -1.18882425 -0.8042535\n44  2.085887418 -1.13376454 -0.2113516\n45 -0.007865673  1.62715521 -1.8920737\n46 -2.354875012  1.25226610 -0.7344787\n47 -0.622007893  1.88331825 -1.2703962\n48  0.246180327 -0.89037300 -1.6181206\n49 -0.674860159 -0.33612045 -1.4240738\n50 -0.961984764  4.44458858 -1.2228367\n```\n:::\n:::\n\n\nBut if you were also collecting data on if a field was being ploughed or not you may have:\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\"1\" = sample(size = 50, x = c(\"Plough\", \"No plough\"), prob = c(0.5, 0.5), replace = TRUE), \n           \"2\" = sample(size = 50, x = c(\"Plough\", \"No plough\"), prob = c(0.1, 0.9), replace = TRUE), \n           \"3\" = sample(size = 50, x = c(\"Plough\", \"No plough\"), prob = c(0.8, 0.2), replace = TRUE), \n           check.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           1         2         3\n1  No plough No plough No plough\n2  No plough No plough    Plough\n3     Plough No plough    Plough\n4     Plough No plough No plough\n5  No plough No plough    Plough\n6  No plough No plough No plough\n7     Plough No plough No plough\n8  No plough No plough    Plough\n9     Plough No plough    Plough\n10 No plough No plough    Plough\n11    Plough No plough No plough\n12    Plough    Plough    Plough\n13 No plough No plough    Plough\n14 No plough No plough    Plough\n15 No plough No plough    Plough\n16 No plough No plough    Plough\n17 No plough No plough    Plough\n18 No plough No plough No plough\n19    Plough No plough No plough\n20    Plough No plough    Plough\n21    Plough No plough    Plough\n22 No plough No plough    Plough\n23 No plough No plough    Plough\n24 No plough No plough No plough\n25    Plough No plough    Plough\n26    Plough No plough No plough\n27 No plough No plough    Plough\n28 No plough No plough    Plough\n29 No plough No plough    Plough\n30 No plough No plough    Plough\n31 No plough No plough    Plough\n32    Plough No plough    Plough\n33 No plough No plough    Plough\n34 No plough No plough No plough\n35    Plough No plough    Plough\n36 No plough No plough    Plough\n37 No plough No plough No plough\n38    Plough No plough    Plough\n39    Plough No plough    Plough\n40 No plough No plough    Plough\n41 No plough No plough No plough\n42 No plough No plough No plough\n43 No plough No plough No plough\n44 No plough No plough    Plough\n45    Plough No plough    Plough\n46 No plough No plough    Plough\n47 No plough No plough    Plough\n48    Plough No plough No plough\n49 No plough No plough    Plough\n50 No plough No plough    Plough\n```\n:::\n:::\n\n\n# What next?\n\nHopefully this page helped give you an understanding of the theory, how to implement it, and how to collect and store your data.\n\nOn the next page, we're going to begin thinking about *Bayesian* statistics. But take a break, go for a walk, do something else for a day or two. Then come back when you're ready.\n",
    "supporting": [
      "OccMods_WithCovariates_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}